### ISSUE TITLE
No emails on Thimble Join

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-login-ux#119] opened 2014-12-22 23:26 UTC
Platform: OS X 10.9.5
Browser: FF Dev 36.0a2

URL: https://thimble.mofostaging.net/

I joined thimble successfully, but did not receive a welcome email. Did not receive an email on sign in either. Repeated 3 times with different addresses to confirm it wasn't spam or typos.

**Comment by jbuck** [comment] 2015-01-05 23:29
I'm going to chalk this up to a transient error in sawmill/lumberyard, probably caused by @secretrobotron's invalid email testing :)

Closing for now.

**Closed by jbuck** 2015-01-05 23:29 UTC
Labels: bug, critical

**Comment by secretrobotron** [comment] 2015-01-05 23:32
# ᕕ( ᐛ)ᕗ
