### ISSUE TITLE
Header in "Explore" section does not reflect logged-in state

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-login-ux#137] opened 2015-01-06 23:23 UTC
Browser: Chrome 39.0.2171.95
Platform: Mac OS 10.10.1

Steps to reproduce:
- Sign-in using an existing account from the splash / landing page
- Navigate to "Explore"
- Header does not reflect logged-in state

![screen shot 2015-01-06 at 3 22 47 pm](https://cloud.githubusercontent.com/assets/747641/5638123/f9b6083c-95b7-11e4-8383-05352f8849a3.png)

**Comment by jbuck** [comment] 2015-01-07 00:59
Dupe of #136

**Closed by jbuck** 2015-01-07 00:59 UTC
Labels: bug, critical
